[project]
name = "pyexamples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "pandas>=2.2.3",
    "text2vec>=1.3.3",
]
